### ISSUE TITLE
HttpHeaders for WebSockets

### ISSUE THREAD

**Issue by fommil** [dcaoyuan/spray-websocket#65]
I noticed that the headers are defined explicitly in the examples:

``` scala
 val headers = ... ::: List(
    HttpHeaders.Connection("Upgrade"),
    HttpHeaders.RawHeader("Upgrade", "websocket"),
    HttpHeaders.RawHeader("Sec-WebSocket-Version", "13"),
    HttpHeaders.RawHeader("Sec-WebSocket-Key", "x3JJHMbDL1EzLkh9GBhXDw=="))
```

Could you please package the upgrade parts in an object so that all client code doesn't need to write this?

**Comment by pangiole** [comment]
I can see a `basicHandshakeRepuset` (mispelled) method at line 73 of src/main/scala/spray/can/websocket/package.scala as added at commit id 55d5909

Is that what you're looking for?
