### ISSUE TITLE
different workers for different endpoints

### ISSUE THREAD

**Issue by fommil** [dcaoyuan/spray-websocket#67]
Perhaps I am misunderstanding, but the `WebSocketServerWorker` appears to ignore the path when an upgrade request is received. This seems to make it impossible to serve different WebSocket server implementations depending on the path element. One obvious example of this might be the protocol version, which must be encoded in a user-defined handshake following the upgrade, but which would be best achieved in the connection request.

**Comment by quant4s** [comment]
oh....  i have the same question.
