### ISSUE TITLE
ack-ing and nack-ing

### ISSUE THREAD

**Issue by fommil** [dcaoyuan/spray-websocket#68]
Akka IO supports acks/nacks for backpressure: http://doc.akka.io/docs/akka/snapshot/scala/io-tcp.html#throttling-reads-and-writes

But I can't find the docs on how to wrap a FrameCommand/FrameStreamCommand (or client Frame/FrameStream) to ask for an ack/nack.

Is this supported?

**Comment by fommil** [comment]
I ended up in FrameRendering and it looks like the `FrameCommand`s (which I find confusing) are being intercepted at this level and turned into NON-Ack `Write` messages. Ignoring backpressure seems to be a major oversight ... is there a workaround or would enabling backpressure be a major refactor for you?

**Comment by fommil** [comment]
Would you be interested if I put together a PR to add ack/nacks to the `FrameCommand` and `FrameStreamCommand`?

I'm not sure how to add the backpressure on the client side.

Also, when you're streaming content out do you use backpressure there or could a slow client potentially cause an OOM on the server?

**Comment by fommil** [comment]
I cannot work out how to hack this library to get backpressure on the client side.

**Comment by TrustNoOne** [comment]
is anyone reading this? 
Have you managed to support backpressure server-side?

**Comment by fommil** [comment]
yeah, check out https://github.com/smootoo/simple-spray-websockets

but it would require a refactor of wandoulab's lib to support it client side.
