### ISSUE TITLE
what is the maskingKey?

### ISSUE THREAD

**Issue by fommil** [dcaoyuan/spray-websocket#69]
In FrameRendering there is a maskingKey that is passed around. What is it and how is it set?

**Comment by dcaoyuan** [comment]
Here:

https://github.com/wandoulabs/spray-websocket/blob/master/spray-websocket%2Fsrc%2Fmain%2Fscala%2Fspray%2Fcan%2Fwebsocket%2FWebSocketServerWorker.scala#L33

You can pass maskGen to pipelineStage:
https://github.com/wandoulabs/spray-websocket/blob/master/spray-websocket%2Fsrc%2Fmain%2Fscala%2Fspray%2Fcan%2Fwebsocket%2FWebSocketServerWorker.scala#L33

**Comment by fommil** [comment]
that seems to be the same link both times. Are you saying that the client can ask for a mask to be applied? I'm guessing that's part of the spec, what is it useful for?

**Comment by cowboy129** [comment]
To avoid attacks on deployed intermediaries, client must pick a masking key from random 32-bit value.

Please refer to http://tools.ietf.org/html/rfc6455#page-51

**Comment by fommil** [comment]
is this ever actually used though? `WebSocketServerWorker` doesn't pass anything --- so the user's mask is ignored.

**Comment by cowboy129** [comment]
Please check `websocket.clientPipelineStage`, you can pass a `maskGen` function to the pipeline.

**Comment by fommil** [comment]
@cowboy129 yes, I see that. But in the client code no such `maskGen` is ever passed, so does this mean it is effectively ignored and users would have to write their own upgrading layer to enable use of the masks?
