### ISSUE TITLE
toString on TextFrame

### ISSUE THREAD

**Issue by fommil** [dcaoyuan/spray-websocket#71]
This would be incredibly useful for debugging Akka (un)-handled message logging.

**Comment by petervandenabeele** [comment]
If I understand correctly, I got something naive for debugging working with
`textFrame.payload.decodeString("ASCII")`

**Comment by Alain-Bearez** [comment]
I would prefer that other implementation which takes only the start of a potentially huge payload message:

```
final class TextFrame(_finRsvOp: Byte, _payload: ByteString) extends Frame(_finRsvOp, _payload) {
  override def toString = _payload.utf8String.take(100)
}
```

**Comment by fommil** [comment]
I think my PR closes this, I forgot to reference them. BTW, somewhat related: https://github.com/akka/akka/issues/17898

Please vote for it.
